INSERT INTO notes (id, folder_id, title, summary, created_at, updated_at) VALUES
(1, 1, 'Anotações de Reunião - Segunda', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ultrices nisi in nunc bibendum tincidunt.', '2026-03-01 08:30:00', NULL),
(2, 2, 'Tutorial de Spring Boot', 'Maecenas leo diam, sodales at massa sit amet, sodales molestie eros. Pellentesque hendrerit a mauris et imperdiet.', '2026-03-02 10:15:00', NULL),
(3, 3, 'Ideias para o Canal', 'Integer urna purus, sodales vitae ligula vel, dapibus luctus metus. Nam nec efficitur mauris.', '2026-03-03 14:20:00', NULL),
(4, 2, 'Setup do Ambiente Python', 'Aliquam ligula metus, rhoncus nec risus vitae, placerat egestas dui. Nulla sodales, purus tempor posuere mollis.', '2026-03-04 09:05:00', NULL),
(5, 4, 'Deploy na AWS', 'Turpis odio rhoncus urna, rutrum venenatis erat nisi eget tortor. Proin viverra, ante et porta blandit.', '2026-03-05 16:40:00', NULL),
(6, 5, 'Referências de Design', 'Est urna ultrices massa, in imperdiet nisl nunc id massa. Nullam porta purus sed felis venenatis eleifend.', '2026-03-06 11:10:00', NULL),
(7, 2, 'Estudo de React Hooks', 'Integer eu lobortis augue, sit amet tincidunt ante. Nunc ultrices nisi in nunc bibendum tincidunt.', '2026-03-07 18:50:00', NULL),
(8, 6, 'Planejamento Semanal', 'Pellentesque hendrerit a mauris et imperdiet. Integer urna purus, sodales vitae ligula vel, dapibus luctus metus.', '2026-03-08 07:00:00', NULL),
(9, 7, 'Podcast: Inteligência Artificial', 'Nam nec efficitur mauris. Aliquam ligula metus, rhoncus nec risus vitae, placerat egestas dui.', '2026-03-09 20:30:00', NULL),
(10, 8, 'Resumo do Livro X', 'Nulla sodales, purus tempor posuere mollis, turpis odio rhoncus urna, rutrum venenatis erat nisi eget tortor.', '2026-03-10 12:00:00', NULL),
(11, 1, 'Bugs para Corrigir (Jira)', 'Proin viverra, ante et porta blandit, est urna ultrices massa, in imperdiet nisl nunc id massa.', '2026-03-11 15:15:00', NULL),
(12, 3, 'Script do Vídeo: Microserviços', 'Nullam porta purus sed felis venenatis eleifend. Integer eu lobortis augue, sit amet tincidunt ante.', '2026-03-12 09:45:00', NULL),
(13, 2, 'Curso de Docker - Módulo 1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas leo diam, sodales at massa sit amet.', '2026-03-13 10:05:00', NULL),
(14, 4, 'Notas de Atualização v2.1', 'Pellentesque hendrerit a mauris et imperdiet. Integer urna purus, sodales vitae ligula vel, dapibus luctus metus.', '2026-03-14 14:30:00', NULL),
(15, 6, 'Lista de Compras de Hardware', 'Aliquam ligula metus, rhoncus nec risus vitae, placerat egestas dui. Nulla sodales, purus tempor posuere mollis.', '2026-03-15 18:20:00', NULL),
(16, 2, 'Como otimizar queries SQL', 'Turpis odio rhoncus urna, rutrum venenatis erat nisi eget tortor. Proin viverra, ante et porta blandit.', '2026-03-16 11:45:00', NULL),
(17, 9, 'Roteiro da Palestra', 'Est urna ultrices massa, in imperdiet nisl nunc id massa. Nullam porta purus sed felis venenatis eleifend.', '2026-03-17 16:00:00', NULL),
(18, 1, 'Revisão de Código - PR #45', 'Integer eu lobortis augue, sit amet tincidunt ante. Nunc ultrices nisi in nunc bibendum tincidunt.', '2026-03-18 09:10:00', NULL),
(19, 3, 'Setup do OBS Studio', 'Maecenas leo diam, sodales at massa sit amet, sodales molestie eros. Nam nec efficitur mauris.', '2026-03-19 13:25:00', NULL),
(20, 4, 'Análise de Concorrentes', 'Aliquam ligula metus, rhoncus nec risus vitae, placerat egestas dui. Nulla sodales, purus tempor posuere mollis.', '2026-03-20 10:50:00', NULL),
(21, 2, 'Testes Unitários em Java', 'Turpis odio rhoncus urna, rutrum venenatis erat nisi eget tortor. Proin viverra, ante et porta blandit.', '2026-03-21 14:15:00', NULL),
(22, 1, 'Log de Erros do Servidor', 'Est urna ultrices massa, in imperdiet nisl nunc id massa. Nullam porta purus sed felis venenatis eleifend.', '2026-03-22 08:05:00', NULL),
(23, 10, 'Ideias para App Mobile', 'Integer eu lobortis augue, sit amet tincidunt ante. Pellentesque hendrerit a mauris et imperdiet.', '2026-03-23 21:30:00', NULL),
(24, 4, 'Configuração de CI/CD', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ultrices nisi in nunc bibendum tincidunt.', '2026-03-24 11:20:00', NULL),
(25, 2, 'Estudo de Caso: Netflix', 'Maecenas leo diam, sodales at massa sit amet, sodales molestie eros. Integer urna purus, sodales vitae.', '2026-03-25 15:45:00', NULL),
(26, 1, 'Pautas para Reunião 1:1', 'Aliquam ligula metus, rhoncus nec risus vitae, placerat egestas dui. Nam nec efficitur mauris.', '2026-03-26 09:30:00', NULL),
(27, 3, 'Thumbnails para os Vídeos', 'Nulla sodales, purus tempor posuere mollis, turpis odio rhoncus urna, rutrum venenatis erat nisi eget tortor.', '2026-03-27 14:10:00', NULL),
(28, 2, 'Aprender TypeScript', 'Proin viverra, ante et porta blandit, est urna ultrices massa, in imperdiet nisl nunc id massa.', '2026-03-28 10:00:00', NULL),
(29, 4, 'Feedback de Usuários', 'Nullam porta purus sed felis venenatis eleifend. Integer eu lobortis augue, sit amet tincidunt ante.', '2026-03-28 16:25:00', NULL),
(30, 6, 'Metas Trimestrais (Q2)', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque hendrerit a mauris et imperdiet.', '2026-03-28 08:15:00', NULL),
(31, 1, 'Refatoração do Módulo de Pagamento', 'Maecenas leo diam, sodales at massa sit amet, sodales molestie eros. Nunc ultrices nisi in nunc.', '2026-03-28 11:50:00', NULL),
(32, 5, 'Equipamentos de Áudio', 'Integer urna purus, sodales vitae ligula vel, dapibus luctus metus. Aliquam ligula metus, rhoncus nec.', '2026-03-28 15:50:00', NULL),
(33, 2, 'Introdução a GraphQL', 'Turpis odio rhoncus urna, rutrum venenatis erat nisi eget tortor. Nulla sodales, purus tempor posuere.', '2026-03-28 09:40:00', NULL),
(34, 10, 'Brainstorm de Projetos Open Source', 'Proin viverra, ante et porta blandit, est urna ultrices massa, in imperdiet nisl nunc id massa.', '2026-04-03 18:30:00', NULL),
(35, 4, 'Migração de Banco de Dados', 'Nullam porta purus sed felis venenatis eleifend. Integer eu lobortis augue, sit amet tincidunt ante.', '2026-03-28 10:10:00', NULL);

SELECT setval('notes_id_seq', (SELECT MAX(id) FROM notes));